language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

jobs:
  include:
    - name: Unit Test and Deploy If Pushing a Tag
      script: ./gradlew build
      deploy:
        provider: releases
        api_key:
          secure: ZZTei505SVPqwjy174Mjl+d597k2uKtCz2YUMzy7paApyRxFfSBBXtUyzwgiHPzlX4i9g2+o6F0xkCqcGDQb3TEbbklp8QRW+ccXFJ1iusH7KtjKgnGlf0CPuHFauD0bcFZSsfOxGeFieUKY6X3rCpUFMwR5asllgaKoH20MEMvlMlMYBpV1Demxgz22j9Hckb5PfXK46K7Vsf3QZqeJj6i+jon05o5ziNTlPFZ9700Nx0voeNnCRuTENeDJk5PCHj3WyH3CUc13a/lhVZqPAarAviiVTrqAgXxjxs3ijYoK8YWbi64BP3KKJxLRuashna74U/2/tqFYRs0xS0RSntwdSeqUMwWsVPqBE/2SlRBcFBIZeQ5Og+QWb7e4R12EU4Nqgz4l7B2apsGRCnw2iyFnJQPRCY9nL9opdpk1L06LEDQ2VkbhfGc+gg4/wm2PWXoZX4fFgvtv5Q54qbsBaa2Ia7KEWsz5pOzugLo/RKWtu9Hy6pH1oz0RBsgIo6jhQoAmQHAaQdc3WldLC8bepJW4kRerTzhZ6NqCOV5JlbtqjyUkEOBjdZ45/Y88TIZyYtAKqBwqW89SNVHxqw6uqYbqCRNdj1sVxCzWOojP/n2BxpwXLnOfODe5MfeUK6uoeDv0QQHGlOXjuPoYcW9yuimgrBO+BPSkkP3dE/7ir8o=
        skip_cleanup: true
        file_glob: true
        file: build/libs/*
        on:
          repo: breadoliveoilsalt/http-server-java
          all_branches: true
          tags: true
    - name: Run Acceptance Tests
      script: ./scripts/acceptance_tests.sh
